### ISSUE TITLE
About training hyperparameter settings？

### ISSUE THREAD

**Issue by zhanghongyong123456** [SHI-Labs/VMFormer#12]
1. about   input  images  Sequence T， paper  table 1 (e)  ) Number of Queries   5 > 10 , Compared to RVM  set  T  （15 -> 40 ）,Is the larger the T the stronger the temporality, and why our experimental results are the opposite
2. I found that our data resolution is 512x288，The small resolution training results are already similar to the CNN results，if  Similar to RVM, adding a high-resolution module and using high-resolution training data（like  2048 ）, will the effect be improved? Or do we use 2048*2048 resolution, which directly out of memory？ GPU for training 8 * RTX A6000 GPU （48G  ），I think  the memory is too large 
3. about FPS ，Is there an improvement,  is it very slow Compared to  other state-of-the-art methods，
![image](https://user-images.githubusercontent.com/48466610/197327369-0de9d31f-cc4e-49e1-98ab-48fff5c5a375.png)

**Comment by chrisjuniorli** [comment]
Thanks for reaching out. 
1. When we change the queries from 5 -> 10, we also set the batch size to 1 due to GPU memory as it is mentioned in the ablation study.  We believe this setting could lead to the degradation of performance.
2. High-resolution data training and inference is on our to-do list and we don't have any results yet. We will include this part in the updated version of the paper.
3.  FPS is a bottleneck since we apply a full transformer module in VMFormer. One solution is to only add high-level feature maps for the transformer module so that the total computation drops, while it may hurt the performance at the same time.
